{!!python/unicode 'C_plus': 125000.0, !!python/unicode 'a': 1.0, !!python/unicode 'accu': 0.05,
  !!python/unicode 'average_speed': 50.0, !!python/unicode 'breaking_on_last_hundreds_probability': 0.95,
  !!python/unicode 'cars_quantity': 1.0, !!python/unicode 'cost_loss_by_car_sell': 1000000.0,
  !!python/unicode 'driver__salary': 30000.0, !!python/unicode 'flagDut': 0.0, !!python/unicode 'flagFrLoss': 0.0,
  !!python/unicode 'flagI': 0.0, !!python/unicode 'flagPP': 0.0, !!python/unicode 'flagThermo': 0.0,
  !!python/unicode 'flagTracker': 1.0, !!python/unicode 'flag_alarm_btn': 0.0, !!python/unicode 'flag_block_eng': 0.0,
  !!python/unicode 'flag_passengers': 0.0, !!python/unicode 'fridge__spoil_fee': 50000.0,
  !!python/unicode 'fridge_loss_probability': 0.05, !!python/unicode 'fuel__cost_per_liter': 35.0,
  !!python/unicode 'fuel__liters_per_km': 0.12, !!python/unicode 'fuel__stealing_rate': 0.05,
  !!python/unicode 'fuel__type': 35.0, !!python/unicode 'fuel__usage_increase_by_time_of_workout': 0.275,
  !!python/unicode 'monitoring__abonent_pays_per_month': 300.0, !!python/unicode 'monitoring__alarm_btn_cost': 1000.0,
  !!python/unicode 'monitoring__block_eng_cost': 2000.0, !!python/unicode 'monitoring__dut_cost': 2500.0,
  !!python/unicode 'monitoring__pp': 3000.0, !!python/unicode 'monitoring__termometr_cost': 2000.0,
  !!python/unicode 'monitoring__tracker_cost': 4500.0, !!python/unicode 'motorhours_per_day': 5.0,
  !!python/unicode 'payload': 5.0, !!python/unicode 'prob': 500000.0, !!python/unicode 'repair__year_cost_new_car': 20000.0,
  !!python/unicode 'service__price_part_per_year': 0.05, !!python/unicode 'work__cost_per_tkm': 5.0,
  !!python/unicode 'workdays_per_year': 250.0, !!python/unicode 'x_k': 0.8}
